version: '3'
services:
  mysql:
    image: mysql:5.7
    build: ./mysql
    environment:
      - MYSQL_DATABASE=cp
      - MYSQL_ROOT_PASSWORD=cui,logic
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  web:
    build: ./APP
    ports:
     - "5000:5000"
    links:
     - mysql:mysql
    depends_on:
     - mysql
